---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nickjufg/nodejs
    - /bin/cp -R /home/nickjufg/repositories/PolicyBook $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/PolicyBook/.git
    - /bin/rm -rf $DEPLOYPATH/PolicyBook/.gitignore