---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nickjufg/nodejs
    - /bin/cp -R /home/nickjufg/repositories/devPolicyBook $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/devPolicyBook/.git
    - /bin/rm -rf $DEPLOYPATH/devPolicyBook/.gitignore